// Copyright 2026 The Omnix Authors
// SPDX-License-Identifier: Apache-2.0

import 'dart:typed_data';

import '../capabilities/omnix_capability_registry_snapshot.dart';
import '../models/omnix_model_manifest.dart';

/// Settings for one local agent session.
final class OmnixAgentConfiguration {
  /// Creates settings for a model-backed agent session.
  const OmnixAgentConfiguration({
    required this.modelTemplate,
    this.preferredBackend = OmnixBackendPreference.cpu,
    this.maxTokens = 4096,
    this.maxOutputTokens,
    this.maxSteps = 10,
    this.temperature = 0.8,
    this.randomSeed = 1,
    this.topK = 1,
    this.topP,
    this.supportsFunctionCalls = true,
    this.supportsImages = false,
    this.supportsAudio = false,
    this.systemPromptTemplate,
  });

  /// Prompt and tokenizer context capacity requested from the model backend.
  final int maxTokens;

  /// Maximum tokens generated by one model iteration, when constrained.
  final int? maxOutputTokens;

  /// Maximum model/tool iterations permitted for one turn.
  final int maxSteps;

  /// Model family whose chat template should be used.
  final OmnixModelTemplate modelTemplate;

  /// Preferred accelerator, with provider-defined fallback behavior.
  final OmnixBackendPreference preferredBackend;

  /// Sampling temperature.
  final double temperature;

  /// Reproducible sampling seed.
  final int randomSeed;

  /// Top-k sampling limit.
  final int topK;

  /// Nucleus sampling threshold, when specified.
  final double? topP;

  /// Whether the model session advertises function calling.
  final bool supportsFunctionCalls;

  /// Whether turns may include image bytes.
  final bool supportsImages;

  /// Whether the model session advertises audio input support.
  final bool supportsAudio;

  /// Optional provider-compatible prompt containing a `__SKILLS__` marker.
  ///
  /// When omitted, the agent backend uses its own default discovery prompt.
  final String? systemPromptTemplate;
}

/// A structured value returned by an agent tool.
sealed class OmnixAgentToolOutput {
  const OmnixAgentToolOutput();
}

/// Plain text returned by a tool.
final class OmnixAgentTextOutput extends OmnixAgentToolOutput {
  const OmnixAgentTextOutput(this.text);

  final String text;
}

/// Encoded image bytes returned by a tool.
final class OmnixAgentImageOutput extends OmnixAgentToolOutput {
  const OmnixAgentImageOutput(this.bytes);

  final Uint8List bytes;
}

/// A web resource returned by a tool.
final class OmnixAgentWebOutput extends OmnixAgentToolOutput {
  const OmnixAgentWebOutput(this.uri, {required this.embed});

  final Uri uri;
  final bool embed;
}

/// A tool failure returned as data so the model may recover.
final class OmnixAgentErrorOutput extends OmnixAgentToolOutput {
  const OmnixAgentErrorOutput(this.message);

  final String message;
}

/// A provider result that cannot cross the headless Omnix boundary.
///
/// For example, a provider may return a framework-native view. Hosts can still
/// show a useful summary without Omnix exposing that framework type.
final class OmnixAgentUnavailableOutput extends OmnixAgentToolOutput {
  const OmnixAgentUnavailableOutput({required this.kind, this.description});

  final String kind;
  final String? description;
}

/// A progress or response event emitted during an agent turn.
sealed class OmnixAgentEvent {
  const OmnixAgentEvent();
}

/// The agent attempted to load one skill's instructions.
final class OmnixAgentSkillLoad extends OmnixAgentEvent {
  const OmnixAgentSkillLoad({required this.skillId, required this.found});

  final String skillId;
  final bool found;
}

/// The agent requested execution of a tool.
final class OmnixAgentToolCall extends OmnixAgentEvent {
  const OmnixAgentToolCall({
    required this.name,
    required this.arguments,
    this.skillId,
  });

  final String name;
  final Map<String, Object?> arguments;
  final String? skillId;
}

/// A tool finished and returned a structured [output].
final class OmnixAgentToolResult extends OmnixAgentEvent {
  const OmnixAgentToolResult({required this.name, required this.output});

  final String name;
  final OmnixAgentToolOutput output;
}

/// One visible text fragment from the agent's final answer.
final class OmnixAgentTextDelta extends OmnixAgentEvent {
  const OmnixAgentTextDelta(this.text);

  final String text;
}

/// The agent completed a turn with [text] as its accumulated answer.
final class OmnixAgentCompleted extends OmnixAgentEvent {
  const OmnixAgentCompleted(this.text);

  final String text;
}

/// The agent stopped after reaching its configured iteration guard.
final class OmnixAgentStepLimitReached extends OmnixAgentEvent {
  const OmnixAgentStepLimitReached(this.steps);

  final int steps;
}

/// A recoverable or terminal failure surfaced by the agent loop.
final class OmnixAgentFailure extends OmnixAgentEvent {
  const OmnixAgentFailure(this.message, {this.toolName});

  final String message;
  final String? toolName;
}

/// A stateful agent session backed by one local model conversation.
abstract interface class OmnixAgentSession {
  /// Runs one user turn and streams orchestration and answer events.
  Stream<OmnixAgentEvent> ask(String prompt, {Uint8List? imageBytes});

  /// Requests cancellation of the active turn.
  Future<void> stop();

  /// Releases the model session and related native resources.
  Future<void> close();
}

/// Backend capable of opening local agent sessions.
abstract interface class OmnixAgentBackend {
  /// Opens a session using the supplied immutable capability state.
  Future<OmnixAgentSession> openAgent(
    OmnixAgentConfiguration configuration,
    OmnixCapabilityRegistrySnapshot capabilities,
  );
}
