// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Starts a paired, public-Knowledge-only A2A endpoint on local loopback.
///
/// The host must supply a reachable HTTPS origin and own any TLS proxy. The
/// callback is invoked only after the remote peer's signed proof is verified.
/// An empty answer denies the request. No private Knowledge or actions are
/// exposed. Restart the listener after modifying peer grants.
Future<NexusListenerInfo> startPublicKnowledgeListener({
  required String nodeDir,
  required String advertisedOrigin,
  required int port,
  required FutureOr<String> Function(String, String) answer,
}) => RustLib.instance.api.crateApiNexusStartPublicKnowledgeListener(
  nodeDir: nodeDir,
  advertisedOrigin: advertisedOrigin,
  port: port,
  answer: answer,
);

/// Stops a listener started by this process.
Future<void> stopPublicKnowledgeListener({required BigInt id}) =>
    RustLib.instance.api.crateApiNexusStopPublicKnowledgeListener(id: id);

/// Creates this node's local signing identity; refuses to replace one.
Future<String> createNodeIdentity({required String nodeDir}) =>
    RustLib.instance.api.crateApiNexusCreateNodeIdentity(nodeDir: nodeDir);

/// Returns this node's existing public key without creating another identity.
Future<String> nodePublicKey({required String nodeDir}) =>
    RustLib.instance.api.crateApiNexusNodePublicKey(nodeDir: nodeDir);

/// Grants a pinned peer key access to public Knowledge only.
Future<void> allowPublicPeer({
  required String nodeDir,
  required String publicKey,
}) => RustLib.instance.api.crateApiNexusAllowPublicPeer(
  nodeDir: nodeDir,
  publicKey: publicKey,
);

/// Revokes a public Knowledge grant. A running receiver must reload grants.
Future<void> denyPublicPeer({
  required String nodeDir,
  required String publicKey,
}) => RustLib.instance.api.crateApiNexusDenyPublicPeer(
  nodeDir: nodeDir,
  publicKey: publicKey,
);

/// Sends one signed public Knowledge request to a remote A2A node.
Future<NexusKnowledgeReply> queryPeerPublicKnowledge({
  required String nodeDir,
  required String remoteOrigin,
  required String question,
}) => RustLib.instance.api.crateApiNexusQueryPeerPublicKnowledge(
  nodeDir: nodeDir,
  remoteOrigin: remoteOrigin,
  question: question,
);

/// Text artifacts from an authorized peer's completed A2A response.
class NexusKnowledgeReply {
  final String? taskId;
  final List<String> texts;

  const NexusKnowledgeReply({this.taskId, required this.texts});

  @override
  int get hashCode => taskId.hashCode ^ texts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NexusKnowledgeReply &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          texts == other.texts;
}

/// A loopback-only A2A listener managed by the host application.
class NexusListenerInfo {
  final BigInt id;
  final int port;

  const NexusListenerInfo({required this.id, required this.port});

  @override
  int get hashCode => id.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NexusListenerInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          port == other.port;
}
