// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Creates this node's local signing identity; refuses to replace one.
Future<String> createNodeIdentity({required String nodeDir}) =>
    RustLib.instance.api.crateApiNexusCreateNodeIdentity(nodeDir: nodeDir);

/// Returns this node's existing public key without creating another identity.
Future<String> nodePublicKey({required String nodeDir}) =>
    RustLib.instance.api.crateApiNexusNodePublicKey(nodeDir: nodeDir);

/// Grants a pinned peer key access to public Knowledge only.
Future<void> allowPublicPeer({
  required String nodeDir,
  required String publicKey,
}) => RustLib.instance.api.crateApiNexusAllowPublicPeer(
  nodeDir: nodeDir,
  publicKey: publicKey,
);

/// Revokes a public Knowledge grant. A running receiver must reload grants.
Future<void> denyPublicPeer({
  required String nodeDir,
  required String publicKey,
}) => RustLib.instance.api.crateApiNexusDenyPublicPeer(
  nodeDir: nodeDir,
  publicKey: publicKey,
);

/// Sends one signed public Knowledge request to a remote A2A node.
Future<NexusKnowledgeReply> queryPeerPublicKnowledge({
  required String nodeDir,
  required String remoteOrigin,
  required String question,
}) => RustLib.instance.api.crateApiNexusQueryPeerPublicKnowledge(
  nodeDir: nodeDir,
  remoteOrigin: remoteOrigin,
  question: question,
);

/// Text artifacts from an authorized peer's completed A2A response.
class NexusKnowledgeReply {
  final String? taskId;
  final List<String> texts;

  const NexusKnowledgeReply({this.taskId, required this.texts});

  @override
  int get hashCode => taskId.hashCode ^ texts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NexusKnowledgeReply &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          texts == other.texts;
}
